#!/bin/sh
# $Id: test_next_c,v 1.1 2005/02/14 17:47:15 allenh Exp $
#
# Run a test of the mgdb "next" command, constrained to the Consumer process.

{
    mgdb run.x | \
    sed -n '
        s/{//g
        s/}//g
        /^38/p
        /^39/p
        /^41/p
        s/^.*\(monitor>.*\)/\1/
        /^monitor>.*Consumer/p
        s/^\(monitor> *\)Producer.\(.*\)/\1ProducerX\2/p
    ';
    echo "-"
} << END_CMDS 2>/dev/null
set pagination off
break C.mmm:36
run
delete
next
display r
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
next
mwhere
quit
END_CMDS
