#!/bin/sh
#
# $Id: testflowcontrol,v 1.3 2004/09/03 21:12:54 allenh Exp $
# Author: Allen Hopkins
# 
# A simple test run of mgdb, using canned input, and cooking down the output
# for comparison to expected output.

METRO=../../..
${METRO}/bin/mgdb -x testcommands.txt run.x  2>&1 | \
awk '/>>>>/ {p = 1; next;}
     /<<<</ {p = 0; next;}
     p == 1 && /test:$/ {print $0}
     p == 1 && /^Breakpoint/ {place = $NF
                              split(place, a, ":")
                              n = split(a[1], b, "/")
                              print b[n] ":" a[2]}'
echo "-"
