# This makefile is automatically generated by Metropolis.

ROOT =      $(METRO)

CONFIG =    $(ROOT)/mk/metro.mk
include $(CONFIG)

CXX_INCLUDES = -I. $(INCDIR) -I$(SYSTEMC_BACKEND) -I$(SYSTEMC_BACKEND)/util -I$(SYSTEMC_BACKEND)/ltl2ba-1.0 -I$(SYSTEMC_BACKEND)/zchaff -I$(SYSTEMC)/include

LIBRARIES_PATH = -L. -L.. $(LIBDIR) -L$(SYSTEMC_BACKEND)/util -L$(SYSTEMC_BACKEND)/ltl2ba-1.0 -L$(SYSTEMC_BACKEND)/zchaff -L$(SYSTEMC_BACKEND) -L$(SYSTEMC)/$(SYSTEMC_LIB)

all: bin

$(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.o : \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.cpp \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c $(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.cpp \
		-o $(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.o

./Exec.o : ./Exec.cpp ./Exec.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c ./Exec.cpp -o ./Exec.o $(COMPFLAGS) 

$(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.o : \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.cpp \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c $(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.cpp \
		-o $(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.o

./Fetch.o : ./Fetch.cpp ./Fetch.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c ./Fetch.cpp -o ./Fetch.o

./strongarm_netlist.o : ./strongarm_netlist.cpp ./strongarm_netlist.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c ./strongarm_netlist.cpp -o ./strongarm_netlist.o

$(METRO)/lib/metamodel/plt/yapitemplate/yapi.o : \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapi.cpp \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapi.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c $(METRO)/lib/metamodel/plt/yapitemplate/yapi.cpp \
		-o $(METRO)/lib/metamodel/plt/yapitemplate/yapi.o

./MyDataTypes.o : ./MyDataTypes.cpp ./MyDataTypes.h 
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c ./MyDataTypes.cpp -o ./MyDataTypes.o

bin : $(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.o \
		./Exec.o \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.o \
		./Fetch.o ./strongarm_netlist.o \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapi.o ./MyDataTypes.o \
		sc_main.o
	 $(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		$(LIBRARIES_PATH) \
		-o strongarm.x \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapicosim.o \
		./Exec.o \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapidatatypes.o \
		./Fetch.o \
		./strongarm_netlist.o \
		$(METRO)/lib/metamodel/plt/yapitemplate/yapi.o \
		./MyDataTypes.o \
		disarm.o swarm.o tracesim.o trace.o alu.o \
		sc_main.o $(ARCHIVES) $(LINKFLAGS) $(LINKLIBS) \
		-lsystemc -lm -llibrary \
		-lutil -lltl2ba -lsat $(LIBS)

sc_main.o : ./sc_main.cpp
	$(METRO_CXX) $(CXX_FLAGS) $(CXX_INCLUDES) \
		-c ./sc_main.cpp

# Get the rest of the rules
include $(ROOT)/mk/metrocommon.mk
